version: '3'
services:
  api:
    build: .
    ports:
      - '3000:3000'
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - MONGO_URI=${MONGO_URI}
      - POSTGRES_URI=${POSTGRES_URI}
    depends_on:
      - mongodb
      - postgres
  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: api-snx-postgres
    ports:
      - '5432:5432'
